# Generated by Django 5.1.7 on 2025-04-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_achivement_alter_skill_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achivement',
            new_name='Achievement',
        ),
    ]
