# Generated by Django 5.1.7 on 2025-04-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_rename_achivement_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
